server:
  port: 8080
spring:
  application:
    name: kokomi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'QQ1063627264.'
    url: jdbc:mysql://localhost:3306/kokomi?userUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
mybatis:
  # 映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 把蛇形->驼峰
    map-underscore-to-camel-case: true