/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/modules/Avatar.vue')['default']
    BottomNavbar: typeof import('./src/components/navbar/BottomNavbar.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    CodeHighlighted: typeof import('./src/components/articles/CodeHighlighted.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconClearButton: typeof import('./src/components/icons/IconClearButton.vue')['default']
    IconContact: typeof import('./src/components/icons/IconContact.vue')['default']
    IconDark: typeof import('./src/components/icons/IconDark.vue')['default']
    IconDoubleArrow: typeof import('./src/components/icons/IconDoubleArrow.vue')['default']
    IconEye: typeof import('./src/components/icons/IconEye.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconLight: typeof import('./src/components/icons/IconLight.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconMore: typeof import('./src/components/icons/IconMore.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconUpload: typeof import('./src/components/icons/IconUpload.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    InputLine: typeof import('./src/components/inputs/InputLine.vue')['default']
    InputSearch: typeof import('./src/components/inputs/InputSearch.vue')['default']
    LoginModal: typeof import('./src/components/modules/LoginModal.vue')['default']
    MobileNavbar: typeof import('./src/components/navbar/MobileNavbar.vue')['default']
    PostCard: typeof import('./src/components/cards/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/buttons/ThemeToggle.vue')['default']
    TopNavbar: typeof import('./src/components/navbar/TopNavbar.vue')['default']
  }
}
