/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/modules/Avatar.vue')['default']
    BottomNavbar: typeof import('./src/components/navbar/BottomNavbar.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    CodeHighlighted: typeof import('./src/components/articles/CodeHighlighted.vue')['default']
    Dropdown: typeof import('./src/components/modules/Dropdown.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconArrow: typeof import('./src/components/icons/IconArrow.vue')['default']
    IconClearButton: typeof import('./src/components/icons/IconClearButton.vue')['default']
    IconClose: typeof import('./src/components/icons/IconClose.vue')['default']
    IconComment: typeof import('./src/components/icons/IconComment.vue')['default']
    IconContact: typeof import('./src/components/icons/IconContact.vue')['default']
    IconDark: typeof import('./src/components/icons/IconDark.vue')['default']
    IconDoubleArrow: typeof import('./src/components/icons/IconDoubleArrow.vue')['default']
    IconDownload: typeof import('./src/components/icons/IconDownload.vue')['default']
    IconEye: typeof import('./src/components/icons/IconEye.vue')['default']
    IconFlip: typeof import('./src/components/icons/IconFlip.vue')['default']
    IconForward: typeof import('./src/components/icons/IconForward.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconLight: typeof import('./src/components/icons/IconLight.vue')['default']
    IconLike: typeof import('./src/components/icons/IconLike.vue')['default']
    IconLikes: typeof import('./src/components/icons/IconLikes.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconMore: typeof import('./src/components/icons/IconMore.vue')['default']
    IconPerson: typeof import('./src/components/icons/IconPerson.vue')['default']
    IconRotate: typeof import('./src/components/icons/IconRotate.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconShare: typeof import('./src/components/icons/IconShare.vue')['default']
    IconUpload: typeof import('./src/components/icons/IconUpload.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    IconZoomIn: typeof import('./src/components/icons/IconZoomIn.vue')['default']
    IconZoomOut: typeof import('./src/components/icons/IconZoomOut.vue')['default']
    InputLine: typeof import('./src/components/inputs/InputLine.vue')['default']
    InputSearch: typeof import('./src/components/inputs/InputSearch.vue')['default']
    InputTextarea: typeof import('./src/components/inputs/InputTextarea.vue')['default']
    LoginModal: typeof import('./src/components/modules/LoginModal.vue')['default']
    MobileNavbar: typeof import('./src/components/navbar/MobileNavbar.vue')['default']
    Pagination: typeof import('./src/components/modules/Pagination.vue')['default']
    PostCard: typeof import('./src/components/posts/PostCard.vue')['default']
    PostComment: typeof import('./src/components/posts/PostComment.vue')['default']
    PostImage: typeof import('./src/components/posts/PostImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/buttons/ThemeToggle.vue')['default']
    Tooltip: typeof import('./src/components/modules/Tooltip.vue')['default']
    TopNavbar: typeof import('./src/components/navbar/TopNavbar.vue')['default']
  }
}
